OBS_HEIGHT = 42
OBS_WIDTH = 42
OBS_CHANNELS = 1
FRAME_STACK = 5
NUM_ACTIONS = 2

CNN_FILTERS = [32, 64, 64]
CNN_KERNEL_SIZES = [8, 4, 3]
CNN_STRIDES = [4, 2, 1]

FC_UNITS = 256

LEARNING_RATE = 3e-4
CRITIC_LEARNING_RATE = 3e-4

PIXEL_SCALE = 255.0

GAMMA = 0.99

PPO_CLIP_EPSILON = 0.2
PPO_EPOCHS = 4
PPO_MINIBATCH_SIZE = 64


# Sampling hyperparameters.
# Number of trajectories to collect per batch.
NUM_TRAJECTORIES = 100
# Maximum number of steps per trajectory.
MAX_NUM_STEPS = 200

REWARD_STD = 1.0
REWARD_PASSED_PIPE = 2.5
REWARD_DIE = -115.0
