OBS_HEIGHT = 42
OBS_WIDTH = 42
OBS_CHANNELS = 1
FRAME_STACK = 5
NUM_ACTIONS = 2

CNN_FILTERS = [32, 64, 64]
CNN_KERNEL_SIZES = [8, 4, 3]
CNN_STRIDES = [4, 2, 1]

FC_UNITS = 256

LEARNING_RATE = 3e-4
CRITIC_LEARNING_RATE = 3e-4

PIXEL_SCALE = 255.0

GAMMA = 0.995
GAE_LAMBDA = 0.95

PPO_CLIP_EPSILON = 0.2
PPO_TARGET_KL = 0.015
PPO_ENTROPY_COEFFICIENT_START = 0.01
PPO_ENTROPY_COEFFICIENT_END = 0.001
PPO_ENTROPY_DECAY_EPOCHS = 150
PPO_EPOCHS = 4
PPO_MINIBATCH_SIZE = 256


# Sampling hyperparameters.
PPO_ROLLOUT_STEPS = 2048
NUM_ENVS = 32
# Keep this above the first-pipe horizon; 64-step caps prevent score learning.
MAX_NUM_STEPS = 300000

# Use the real C++ game simulation by default; "fast" is an opt-in approximation.
TRAIN_ENV_BACKEND = "cpp_vector"
VALIDATION_EPISODES = 5
VALIDATION_MAX_STEPS = 300000
VALIDATION_TARGET_SCORE = 10000

# Reward scale favors actual score progress over merely surviving rollout fragments.
REWARD_STD = 0.01
REWARD_PASSED_PIPE = 10.0
REWARD_DIE = -10.0
